name: 领红包

# https://docs.github.com/cn/actions/reference/events-that-trigger-workflows#workflow_dispatch
on:
  # 手动触发
  workflow_dispatch:
  schedule:
    # https://crontab.guru/
    # UTC 时间，中国时区应减 8
    #         ┌────────── minute (0 - 59)
    #         │ ┌──────── hour (0 - 23)
    #         │ │ ┌────── day of the month (1 - 31)
    #         │ │ │ ┌──── month (1 - 12 or JAN-DEC)
    #         │ │ │ │ ┌── day of the week (0 - 6 or SUN-SAT)
    #         │ │ │ │ │
    - cron: '45 2 * * *'

jobs:
  start:
    name: grab coupon
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with: { ref: main }
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - name: Run app
        run: yarn start
        env:
          TOKEN: ${{ secrets.TOKEN }}
          BARK_KEY: ${{ secrets.BARK_KEY }}
          TG_USER_ID: ${{1864066149 }}
          TG_BOT_TOKEN: ${{1798023428:AAHQKzbhGRmomCxe1kZVc3uKX2RbZdoH9yo }}
          SC_SEND_KEY: ${{ secrets.SC_SEND_KEY }}
          QYWX_SEND_CONF: ${{ secrets.QYWX_SEND_CONF }}
          LARK_WEBHOOK: ${{ secrets.LARK_WEBHOOK }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
